version: '1'
services:
  back:
    restart: on-failure
    build: .
    depends_on:
      - postgres_db
    environment:
        DATABASE_URL: postgres://postgres:postgres@postgres_db:5432/postgres
        NODE_ENV: development
        PORT: 5450
    ports:
        - "5450:5450"
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
  postgres_db:
    image: postgres
    ports:
      - "35432:5432"
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
