version: '1'
services:
  front:
      build: ./add-scrapper-front
      ports:
      - "8080:80"
      volumes:
        - ./add-scrapper-front:/dist/src/app
  back:
    #restart: on-failure
    build:
      context: ./add-scrapper-back
      dockerfile: Dockerfile
    depends_on:
      postgres_db:
        condition: service_healthy
    links:
      - postgres_db
    command: npm run start
    environment:
        DATABASE_URL: postgres://postgres:password@postgres_db:5432/postgres
        DB_HOST: postgres_db
        NODE_ENV: development
        PORT: 5450
    ports:
        - "5450:5450"
    volumes:
      - ./add-scrapper-back:/usr/src/app
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  postgres_db:
    image: postgres
    ports:
      - "35432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/dbdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

